# Generated by Django 6.0.8 on 2026-09-26 03:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='departamento')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='municipio')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='dirección')),
                ('total_area_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='área total (ha)')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'finca',
                'verbose_name_plural': 'fincas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='área (ha)')),
                ('current_tree_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='árboles actuales')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FALLOW', 'En descanso'), ('RETIRED', 'Retirado')], default='ACTIVE', max_length=8, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='agriculture.farm', verbose_name='finca')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['farm__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(choices=[('NEW', 'Establecimiento nuevo'), ('RENEWAL', 'Renovación'), ('SOCA', 'Soca'), ('REPLANTING', 'Resiembra'), ('OTHER', 'Otro')], max_length=10, verbose_name='tipo de ciclo')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('planted_tree_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='árboles establecidos')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_cycles', to='agriculture.lot', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'ciclo de cultivo',
                'verbose_name_plural': 'ciclos de cultivo',
                'ordering': ['-start_date', 'lot__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='farm',
            constraint=models.CheckConstraint(condition=models.Q(('total_area_ha__isnull', True), ('total_area_ha__gt', 0), _connector='OR'), name='agri_farm_area_positive_if_set'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('farm', 'code'), name='agri_lot_farm_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('area_ha__gt', 0)), name='agri_lot_area_positive'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('current_tree_count__isnull', True), ('current_tree_count__gt', 0), _connector='OR'), name='agri_lot_tree_count_positive_if_set'),
        ),
        migrations.AddConstraint(
            model_name='cropcycle',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='agri_cycle_end_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='cropcycle',
            constraint=models.CheckConstraint(condition=models.Q(('planted_tree_count__isnull', True), ('planted_tree_count__gt', 0), _connector='OR'), name='agri_cycle_tree_count_positive_if_set'),
        ),
        migrations.AddConstraint(
            model_name='cropcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('lot',), name='agri_cycle_one_open_per_lot'),
        ),
    ]
