# Generated by Django 6.0.8 on 2026-09-26 16:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('FERTILIZATION', 'Fertilización'), ('WEEDING', 'Control de malezas'), ('PRUNING', 'Poda'), ('SPRAYING', 'Aplicación'), ('PEST_CONTROL', 'Control de plagas'), ('DISEASE_CONTROL', 'Control de enfermedades'), ('IRRIGATION', 'Riego'), ('SOIL_MANAGEMENT', 'Manejo del suelo'), ('PLANTING', 'Siembra'), ('OTHER', 'Otra actividad')], max_length=20, verbose_name='tipo de actividad')),
                ('performed_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha realizada')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='agriculture.cropcycle', verbose_name='ciclo de cultivo')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_agricultural_activities', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'actividad agrícola',
                'verbose_name_plural': 'actividades agrícolas',
                'ordering': ['-performed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(blank=True, max_length=160, verbose_name='nombre del trabajador')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='horas')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='tarifa por hora (COP)')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agricultural_labor_records', to=settings.AUTH_USER_MODEL, verbose_name='trabajador con usuario')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_records', to='agriculture.agriculturalactivity', verbose_name='actividad')),
            ],
            options={
                'verbose_name': 'mano de obra de actividad',
                'verbose_name_plural': 'mano de obra de actividades',
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hours__gt', 0)), name='agri_labor_hours_positive'), models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 0)), name='agri_labor_hourly_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('performed_by__isnull', False), models.Q(('worker_name', ''), _negated=True), _connector='OR'), name='agri_labor_has_worker_identifier')],
            },
        ),
        migrations.CreateModel(
            name='ActivityInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='cantidad')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agricultural_activity_inputs', to='products.product', verbose_name='producto')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inputs', to='agriculture.agriculturalactivity', verbose_name='actividad')),
            ],
            options={
                'verbose_name': 'insumo de actividad',
                'verbose_name_plural': 'insumos de actividad',
                'ordering': ['created_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='agri_activity_input_quantity_positive')],
            },
        ),
    ]
