# Generated by Django 6.0.8 on 2026-09-26 16:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_agriculturalactivity_activitylabor_activityinput'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvested_on', models.DateField(verbose_name='fecha de cosecha')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='agriculture.cropcycle', verbose_name='ciclo de cultivo')),
            ],
            options={
                'verbose_name': 'cosecha',
                'verbose_name_plural': 'cosechas',
                'ordering': ['-harvested_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('process_type', models.CharField(choices=[('BENEFIT', 'Beneficio'), ('DRYING', 'Secado'), ('MILLING', 'Trilla'), ('ROASTING', 'Tostión'), ('GRINDING', 'Molienda'), ('OTHER', 'Otro')], max_length=10, verbose_name='tipo de proceso')),
                ('started_at', models.DateTimeField(verbose_name='fecha y hora de inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha y hora de finalización')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_batches', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'lote de producción',
                'verbose_name_plural': 'lotes de producción',
                'ordering': ['-started_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_on', models.DateField(verbose_name='fecha de evaluación')),
                ('factor', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='factor')),
                ('moisture_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='humedad (%)')),
                ('defects_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='defectos (%)')),
                ('broca_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='broca (%)')),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='calificación')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_assessments', to='agriculture.productionbatch', verbose_name='lote de producción')),
            ],
            options={
                'verbose_name': 'evaluación de calidad',
                'verbose_name_plural': 'evaluaciones de calidad',
                'ordering': ['-assessed_on', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='agri_batch_finish_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='qualityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('moisture_pct__isnull', True), models.Q(('moisture_pct__gte', 0), ('moisture_pct__lte', 100)), _connector='OR'), name='agri_quality_moisture_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='qualityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('defects_pct__isnull', True), models.Q(('defects_pct__gte', 0), ('defects_pct__lte', 100)), _connector='OR'), name='agri_quality_defects_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='qualityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('broca_pct__isnull', True), models.Q(('broca_pct__gte', 0), ('broca_pct__lte', 100)), _connector='OR'), name='agri_quality_broca_pct_range'),
        ),
    ]
