# Generated by Django 6.0.8 on 2026-09-26 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_harvest_productionbatch_qualityassessment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_on', models.DateField(verbose_name='fecha de observación')),
                ('problem', models.CharField(max_length=200, verbose_name='problema observado')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=8, verbose_name='severidad')),
                ('observation', models.TextField(verbose_name='observación')),
                ('action_taken', models.TextField(blank=True, verbose_name='acción realizada')),
                ('next_review_on', models.DateField(blank=True, null=True, verbose_name='próxima revisión')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_observations', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_observations', to='agriculture.cropcycle', verbose_name='ciclo de cultivo')),
            ],
            options={
                'verbose_name': 'observación sanitaria',
                'verbose_name_plural': 'observaciones sanitarias',
                'ordering': ['-observed_on', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('next_review_on__isnull', True), ('next_review_on__gte', models.F('observed_on')), _connector='OR'), name='agri_health_review_on_or_after_observed')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Terminada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=12, verbose_name='estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta')], default='NORMAL', max_length=6, verbose_name='prioridad')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='agriculture.agriculturalactivity', verbose_name='actividad agrícola')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agricultural_tasks', to=settings.AUTH_USER_MODEL, verbose_name='asignada a')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agricultural_tasks', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('crop_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='agriculture.cropcycle', verbose_name='ciclo de cultivo')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='agriculture.farm', verbose_name='finca')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='agriculture.lot', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['due_on', '-priority', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('farm__isnull', True), ('lot__isnull', True), _connector='OR'), models.Q(('farm__isnull', True), ('crop_cycle__isnull', True), _connector='OR'), models.Q(('farm__isnull', True), ('activity__isnull', True), _connector='OR'), models.Q(('lot__isnull', True), ('crop_cycle__isnull', True), _connector='OR'), models.Q(('lot__isnull', True), ('activity__isnull', True), _connector='OR'), models.Q(('crop_cycle__isnull', True), ('activity__isnull', True), _connector='OR')), name='agri_task_at_most_one_context'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'DONE')), models.Q(models.Q(('status', 'DONE'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='agri_task_completion_matches_status')],
            },
        ),
    ]
