# Generated by Django 6.0.8 on 2026-09-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='kilos_pergamino',
            field=models.FloatField(default=0, help_text='Kilos pergamino'),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='kilos_added',
            field=models.FloatField(default=0, help_text='Kilos molidos'),
        ),
    ]
