# Generated by Django 6.0.8 on 2026-09-26 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_healthobservation_task'),
        ('expenses', '0001_initial'),
        ('inventory', '0002_inventoryentry_kilos_pergamino_and_more'),
        ('products', '0002_product_base_unit_product_coffee_stage_and_more'),
        ('sales', '0003_saleitem_unit_quantity_base_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'Compra (entrada)'), ('HARVEST_IN', 'Cosecha (entrada)'), ('TRANSFORMATION_IN', 'Transformación (entrada)'), ('ADJUSTMENT_IN', 'Ajuste positivo'), ('OPENING_BALANCE_IN', 'Saldo inicial'), ('AGRICULTURAL_CONSUMPTION_OUT', 'Consumo agrícola (salida)'), ('TRANSFORMATION_OUT', 'Transformación (salida)'), ('SALE_OUT', 'Venta (salida)'), ('ADJUSTMENT_OUT', 'Ajuste negativo')], max_length=32)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('occurred_at', models.DateTimeField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='agriculture.activityinput')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='expenses.expense')),
                ('harvest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movement', to='agriculture.harvest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.product')),
                ('production_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='agriculture.productionbatch')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='sales.saleitem')),
                ('source_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.inventorymovement')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['occurred_at', 'pk'],
                'indexes': [models.Index(fields=['product', 'occurred_at', 'id'], name='inv_mov_product_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inv_move_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='inv_move_unit_cost_nonneg'), models.CheckConstraint(condition=models.Q(('source_movement__isnull', True), models.Q(('source_movement', models.F('id')), _negated=True), _connector='OR'), name='inv_move_source_not_self'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ('PURCHASE_IN', 'HARVEST_IN', 'TRANSFORMATION_IN', 'ADJUSTMENT_IN', 'OPENING_BALANCE_IN')), ('source_movement__isnull', True)), models.Q(('movement_type__in', ('AGRICULTURAL_CONSUMPTION_OUT', 'TRANSFORMATION_OUT', 'SALE_OUT', 'ADJUSTMENT_OUT')), ('source_movement__isnull', False)), _connector='OR'), name='inv_move_source_by_type'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ('ADJUSTMENT_IN', 'ADJUSTMENT_OUT')), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='inv_move_adjustment_reason')],
            },
        ),
    ]
