# Generated by Django 6.0.8 on 2026-09-29

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='operation_key',
            field=models.CharField(
                blank=True,
                help_text='Clave idempotente para operaciones excepcionales y auditables.',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.UniqueConstraint(
                condition=Q(operation_key__isnull=False),
                fields=('operation_key',),
                name='inv_move_operation_key_unique_when_set',
            ),
        ),
    ]
