# Generated by Django 6.0.8 on 2026-09-26 17:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_sale_item_snapshots(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    SaleItem = apps.get_model('sales', 'SaleItem')
    alias = schema_editor.connection.alias

    product_ids = SaleItem.objects.using(alias).values_list('product_id', flat=True).distinct()
    for product in Product.objects.using(alias).filter(pk__in=product_ids).iterator():
        if product.weight_grams is None or product.weight_grams <= 0:
            raise RuntimeError(
                f'No se puede preservar la cantidad histórica: Product {product.pk} no tiene weight_grams positivo.'
            )
        if product.sale_unit_quantity is None or product.sale_unit_quantity <= 0 or not product.base_unit:
            raise RuntimeError(
                f'No se puede completar el catálogo vendible del Product {product.pk} con ventas históricas.'
            )
        if product.sale_price is None or product.sale_price < 0:
            raise RuntimeError(
                f'No se puede marcar vendible el Product {product.pk}: falta un precio válido.'
            )

        Product.objects.using(alias).filter(pk=product.pk).update(is_sellable=True)
        SaleItem.objects.using(alias).filter(product_id=product.pk).update(
            unit_quantity_base_snapshot=product.weight_grams,
        )


def reverse_sale_item_snapshots(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    SaleItem = apps.get_model('sales', 'SaleItem')
    alias = schema_editor.connection.alias
    for item in SaleItem.objects.using(alias).select_related('product').iterator():
        SaleItem.objects.using(alias).filter(pk=item.pk).update(unit_quantity_base_snapshot=None)
    Product.objects.using(alias).update(is_sellable=False)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_base_unit_product_coffee_stage_and_more'),
        ('sales', '0002_sale_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_quantity_base_snapshot',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.RunPython(backfill_sale_item_snapshots, reverse_sale_item_snapshots),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_quantity_base_snapshot',
            field=models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_quantity_base_snapshot__gt', 0)), name='sales_item_snapshot_positive'),
        ),
    ]
