# Generated by Django 6.0.8 on 2026-09-29

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_unit_quantity_base_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='operation_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(
                condition=Q(operation_key__isnull=False),
                fields=('operation_key',),
                name='sales_sale_operation_key_unique_when_set',
            ),
        ),
    ]
