# Generated by Django 6.0.8 on 2026-09-26 17:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_product_catalog(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    alias = schema_editor.connection.alias

    for product in Product.objects.using(alias).all().iterator():
        updates = {}
        if product.weight_grams and product.weight_grams > 0:
            updates['base_unit'] = 'G'
            updates['sale_unit_quantity'] = product.weight_grams

        searchable = f'{product.name} {product.description}'.casefold()
        searchable = searchable.replace('á', 'a').replace('é', 'e').replace('í', 'i').replace('ó', 'o').replace('ú', 'u')
        if 'cafe' in searchable or 'coffee' in searchable:
            if any(token in searchable for token in ('molienda', 'molido', 'ground')):
                updates['item_type'] = 'COFFEE'
                updates['coffee_stage'] = 'GROUND'
            elif any(token in searchable for token in ('pergamino', 'parchment')):
                updates['item_type'] = 'COFFEE'
                updates['coffee_stage'] = 'PARCHMENT'
            elif any(token in searchable for token in ('cereza', 'cherry')):
                updates['item_type'] = 'COFFEE'
                updates['coffee_stage'] = 'CHERRY'
            elif any(token in searchable for token in ('verde', 'green')):
                updates['item_type'] = 'COFFEE'
                updates['coffee_stage'] = 'GREEN'
            elif any(token in searchable for token in ('tostado', 'tostion', 'roasted')):
                updates['item_type'] = 'COFFEE'
                updates['coffee_stage'] = 'ROASTED'

        if updates:
            Product.objects.using(alias).filter(pk=product.pk).update(**updates)


def reverse_product_catalog(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    alias = schema_editor.connection.alias
    Product.objects.using(alias).update(
        item_type=None, coffee_stage=None, base_unit=None, sale_unit_quantity=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(blank=True, choices=[('G', 'Gramo'), ('ML', 'Mililitro'), ('UNIT', 'Unidad')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='coffee_stage',
            field=models.CharField(blank=True, choices=[('CHERRY', 'Cereza'), ('PARCHMENT', 'Pergamino'), ('GREEN', 'Verde'), ('ROASTED', 'Tostado'), ('GROUND', 'Molido')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_stock_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('COFFEE', 'Café'), ('AGRICULTURAL_INPUT', 'Insumo agrícola'), ('TOOL', 'Herramienta'), ('OTHER', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_unit_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_cost',
            field=models.PositiveIntegerField(help_text='Costo histórico/transicional del sistema; no es el costeo basado en inventario y trazabilidad.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_product_catalog, reverse_product_catalog),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_unit_quantity__isnull', True), ('sale_unit_quantity__gt', 0), _connector='OR'), name='cafena_product_sale_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='cafena_product_sale_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coffee_stage__in', ('CHERRY', 'PARCHMENT', 'GREEN', 'ROASTED', 'GROUND')), ('item_type', 'COFFEE')), models.Q(('item_type__isnull', True), ('coffee_stage__isnull', True)), models.Q(models.Q(('item_type', 'COFFEE'), _negated=True), ('coffee_stage__isnull', True)), _connector='OR'), name='cafena_product_coffee_stage_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('is_stock_tracked', False), ('base_unit__in', ('G', 'ML', 'UNIT')), _connector='OR'), name='cafena_product_tracked_has_unit'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('is_sellable', False), models.Q(('sale_price__isnull', False), ('sale_unit_quantity__gt', 0), ('base_unit__in', ('G', 'ML', 'UNIT'))), _connector='OR'), name='cafena_product_sellable_ready'),
        ),
    ]
