# Generated by Django 6.0.8 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_base_unit_product_coffee_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='production_cost',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Costo histórico/transicional del sistema; no es el costeo basado en inventario y trazabilidad.',
                null=True,
            ),
        ),
    ]
